server:
  port: 8763
spring:
  application:
    name: file-center
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  server:
    enable-self-preservation: false
logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/diskLog/file
hadoop:
  hdfs:
    ip: localhost
    port: 9000
