server:
  port: 8764
spring:
  application:
    name: file-center
  servlet:
    multipart:
      max-file-size: 1000Mb
      max-request-size: 5000Mb
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  server:
    enable-self-preservation: false
logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/diskLog/file
hadoop:
  hdfs:
    ip: localhost
    port: 9000

#文件临时保存路径
file:
  upload: D:/diskLog/temp
  type:
    pic: bmp,jpg,png,tif,gif,pcx,tga,exif,fpx,svg,psd,cdr,pcd,dxf,ufo,eps,ai,raw,WMF,webp
    video: .avi,.wma,.rmvb,.rm,.flash,.mp4,.mid,.3GP
    doc: txt,doc,xls,ppt,pptx,docx,xml,
    music: .mp3,.wav,.wma,m4a,.mp4,.amr,.ogg,.midi,.mv,.rm
